header-from: ./.config/header.md
version: ""

formatter: markdown table

name:  terraform-aws-transfer-server-custom-idp-user

content: |-
  {{ .Header }}
  
  # terraform-aws-transfer-server-custom-idp-user

  GitHub: [StratusGrid/terraform-aws-transfer-server-custom-idp-user](https://github.com/StratusGrid/terraform-aws-transfer-server-custom-idp-user)

  This is a Terraform module to create users for the AWS SFTP service based on custom identity provider using AWS Secrets Manager. To create the server and the identity provider, use [this module](https://registry.terraform.io/modules/StratusGrid/transfer-server-custom-idp/aws/latest). 
  
  ## Example Usage:
  Create one user to login in the AWS Transfer server.
  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  ---
  
  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---
  
  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - header
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
